name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: true

      - name: Configure MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Verify Qt installation
        shell: bash
        run: |
          echo "Qt6_DIR=$Qt6_DIR"
          ls "$Qt6_DIR/lib/cmake" || true

      - name: Configure (CMake, Ninja, MSVC)
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS=ON \
            -DCMAKE_PREFIX_PATH="$Qt6_DIR/lib/cmake"

      - name: Build project
        shell: bash
        run: cmake --build build --config Release -- -v

      - name: Run unit tests
        shell: bash
        run: |
          ctest --test-dir build --output-on-failure

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtEx-Build
          path: build/QtEx.exe
